web/intranet/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls
from wagtail_pdf_view import urls as wagtailpdf_urls

from intranet.api import api_router
from users.views import UserPermissionDetailsView, CustomUserIndexView
from administration.views import administration_search
from accompte.views import CustomPasswordChangeView, profile_update, profile_view
from agents.views import faq_filter, faq_search
from django.urls import path

urlpatterns = [
    path("api/v2/auth/", UserPermissionDetailsView.as_view(), name="auth"),
    path("api/v2/registration/", include("dj_rest_auth.registration.urls")),
    path("api/v2/", include("dj_rest_auth.urls")),
    path("api/v2/", api_router.urls),
    path("django-admin/", admin.site.urls),
    path('admin/users/', CustomUserIndexView.as_view(), name='wagtailusers_users'),
    path("admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("faq_filter/", faq_filter, name="faq_filter"),
    path("faq_search/", faq_search, name="faq_search"),
    path("administration/search/", administration_search, name="administration_search"),
    path('pdf/', include(wagtailpdf_urls)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # Note that this only works in development mode (DEBUG = True);
    # in production, you will need to configure your web server to serve files from MEDIA_ROOT.
    # For further details [...] extrait de https://github.com/torchbox/wagtailmedia#url-configuration

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path('account/password/change/', CustomPasswordChangeView.as_view(), name='account_password_change'),
    path("account/", include("allauth.urls")),
    path("account/profile/", profile_view, name="account_profile"),
    path("account/profile/update/", profile_update, name="profile_update"),
    # path('', include(wagtailimport_urls)),
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    # path("pages/", include(wagtail_urls)),
]

web/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from wagtail.search import index
from django.db import models
from django.utils.translation import gettext_lazy as _

from django.db import models
from wagtail.api import APIField

from utils.widgets import (
    CiviliteListe, 
    CommunesListe, 
    FonctionsMairieListe, 
    FonctionsConseilListe, 
    FonctionsBureauListe, 
    FonctionsConferenceListe,
    )

class User(AbstractUser):
    # Ajout de la civilité pour les champs obligatoires
    civility = models.CharField(
        _("civility"),
        max_length=15,
        choices=CiviliteListe.choices,
        default=CiviliteListe.N,
    )
    # Ajout des champs supplémentaires (utilisateur)
    date_of_birth = models.DateField(
        verbose_name=_("Date of birth"), blank=True, null=True
    )
    address1 = models.CharField(
        verbose_name=_("Address line 1"), max_length=1024, blank=True, null=True
    )
    address2 = models.CharField(
        verbose_name=_("Address line 2"), max_length=1024, blank=True, null=True
    )
    zip_code = models.CharField(
        verbose_name=_("Postal Code"), max_length=12, blank=True, null=True
    )
    city = models.CharField(
        verbose_name=_("City"), max_length=1024, blank=True, null=True
    )
    phone_regex = RegexValidator(
        regex=r"^\+(?:[0-9]●?){6,14}[0-9]$",
        message=_(
            "Enter a valid international mobile phone number starting with +(country code)"
        ),
    )
    mobile_phone = models.CharField(
        validators=[phone_regex],
        help_text=_("With country code and no spaces"),
        verbose_name=_("Mobile phone"),
        max_length=17,
        blank=True,
        null=True,
    )    
    # Ajout des champs spécifiques aux élus
    municipality = models.TextField(
        blank=True, 
        null=True,
        choices=CommunesListe.choices,
        # default=CommunesListe.NULL,
        verbose_name=_("municipality"),
    )
    function_municipality = models.TextField(
        blank=True, 
        null=True,
        choices=FonctionsMairieListe.choices,
        # default=FonctionsMairieListe.NULL,
        verbose_name=_("municipal council function"),
    )
    function_council = models.TextField(
        blank=True, 
        null=True,
        choices=FonctionsConseilListe.choices,
        # default=FonctionsConseilListe.NULL,
        verbose_name=_("communautary council function"),
    )
    commissions = models.ManyToManyField(
        'administration.CommissionPage',
        verbose_name=_("commissions"),
        blank=True,
    )
    functions_commissions = models.JSONField(
        default=list, 
        verbose_name=_("Functions in Commissions"),
        blank=True,
    )
    function_bureau = models.TextField(
        blank=True, 
        null=True,
        choices=FonctionsBureauListe.choices,
        # default=FonctionsBureauListe.NULL,
        verbose_name=_("bureau function"),
    )
    function_conference = models.TextField(
        blank=True, 
        null=True,
        choices=FonctionsConferenceListe.choices,
        # default=FonctionsConferenceListe.NULL,
        verbose_name=_("mayor conference function"),
    )
    
    api_fields = [
        APIField('id'),
        APIField('detail_url'),
        APIField('type'),
        APIField('first_name'),
        APIField('last_name'),
        APIField('email'),
        APIField('groups'),
        APIField('user_permissions'),
        APIField('is_staff'),
        APIField('is_active'),
        APIField('date_joined'),
        APIField('last_login'),
        APIField('username'),
        APIField('civility'),
        APIField('date_of_birth'),
        APIField('address1'),
        APIField('address2'),
        APIField('zip_code'),
        APIField('city'),
        APIField('mobile_phone'),
        APIField('municipality'),
        APIField('function_municipality'),
        APIField('function_council'),
        APIField('commissions'),
        APIField('functions_commissions'),
        APIField('function_bureau'),
        APIField('function_conference'),
    ]
    
    search_fields = [
        index.SearchField('civility'),
        index.SearchField('first_name'),
        index.SearchField('last_name'),
        index.SearchField('email'),
        index.FilterField('date_of_birth'),
        index.SearchField('address1'),
        index.SearchField('address2'),
        index.SearchField('zip_code'),
        index.SearchField('city'),
        index.SearchField('mobile_phone'),
        index.SearchField('municipality'),
        index.SearchField('function_municipality'),
        index.SearchField('function_council'),
        index.RelatedFields('commissions', [
            index.SearchField('title'),
        ]),
        index.SearchField('functions_commissions'),
        index.SearchField('function_bureau'),
        index.SearchField('function_conference'),
    ]
        
    class Meta:
        ordering = ["last_name"]
        
    def __str__(self):
        return f"{self.last_name.upper()} {self.first_name}"

web/administration/views.py
from termcolor import colored
from django.shortcuts import render
from django.utils.timezone import datetime
from wagtail.contrib.search_promotions.models import Query

from utils.auth import check_page_access
from administration.models import AdministrationIndexPage, ConvocationPage, CompteRenduPage

def administration_search(request):
    user = request.user
    search_query = request.GET.get('query', None)
    # print(colored(f"search_query: {search_query}", "yellow"))
    start_date = request.GET.get('start_date', None)
    # print(colored(f"start_date: {start_date}", "yellow"))
    end_date = request.GET.get('end_date', None)    
    # print(colored(f"end_date: {end_date}", "yellow"))
    pages = AdministrationIndexPage.objects.first().get_children().live().specific()
    
    convocations, comptes_rendus = cv_cr_filter(user, pages, search_query, start_date, end_date)
    
    return render(
        request,
        "widgets/search/admin_results.html",
        {
            "convocations": convocations,
            "comptes_rendus": comptes_rendus,
            "search_query": search_query,
            "start_date": start_date,
            "end_date": end_date,
        },
    )

# Filtre de recherche pour les convocations et comptes rendus
def cv_cr_filter(user, pages, search_query=None, start_date=None, end_date=None):
    convocations = ConvocationPage.objects.none()
    comptes_rendus = CompteRenduPage.objects.none() 
    
    for page in pages:
        if check_page_access(user, page, False):
            convocations = convocations | ConvocationPage.objects.live().descendant_of(page).order_by('date')
            comptes_rendus = comptes_rendus | CompteRenduPage.objects.live().descendant_of(page).order_by('date')

    if start_date == "single":
        date = datetime.now().date()
        convocations = convocations.filter(date__gte=date).first()
        comptes_rendus = comptes_rendus.filter(date__lte=date).last()
    else:
        if start_date:
            convocations = convocations.filter(date__gte=start_date)
            comptes_rendus = comptes_rendus.filter(date__gte=start_date)
        if end_date:
            convocations = convocations.filter(date__lte=end_date)
            comptes_rendus = comptes_rendus.filter(date__lte=end_date)

    # print(colored(f"convocations: {convocations}", "white", "on_blue"))
    # print(colored(f"comptes_rendus: {comptes_rendus}", "white", "on_blue"))   
    
    if search_query:                       
        convocations = convocations.search(search_query)
        comptes_rendus = comptes_rendus.search(search_query)
        Query.get(search_query).add_hit()
        
    return convocations, comptes_rendus

web/templates/administration/widgets/cv_cr.html
{% if convocation or compte_rendu %}
    <nav class="cgs-nav quickbar administration">
        <ul class="nav-box single">
            {% if convocation %}
                {% with class_type="nav" item=convocation %}
                    {% include 'administration/widgets/li_item.html' %}
                {% endwith %}     
            {% endif %}
            {% if compte_rendu %}   
                {% with class_type="nav" item=compte_rendu %}
                    {% include 'administration/widgets/li_item.html' %}
                {% endwith %}
            {% endif %}
        </ul>
    </nav>
{% endif %}

web/templates/administration/widgets/index_page.html
{% extends "administration/administration_base.html" %}
{% load menu_tags cgs_tags static %}

{% block body_class %}cgs-{{ item_type }} {% if item_type == "commissions" %}menu{% else %}list{% endif %}{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/menu.min.css' %}">
{% endblock extra_css %}

{% block content %}
    {% if item_type == "commissions" %}
        {% with class_type="menu" menu=children show_menu_heading=True logo_type=True %}
            {% include 'administration/widgets/main_item.html' %}
        {% endwith %}
    {% else %}
        {% with class_type="list" menu=children show_menu_heading=True %}
            {% include 'administration/widgets/main_item.html' %}
        {% endwith %}
    {% endif %}
{% endblock %}

{% block footer_mid %}
    {% if item_type == "commission" %}
        {% with class_type="nav" item_type="commissions" menu=commissions_menu logo_type=True index=True %}
            {% include 'administration/widgets/ul_item.html' %}
        {% endwith %}
    {% else %}
        {% with class_type="nav" item_type="administration" menu=admin_menu logo_type=True %}
            {% include 'administration/widgets/ul_item.html' %}
        {% endwith %}
    {% endif %}
{% endblock %}

{% block footer_left %}
    {% administration_quickbar %}     
{% endblock %}

web/templates/administration/widgets/li_item.html
{% load wagtailcore_tags cgs_tags static %}

{% with item=item.specific %}
    {% if item %}
        <li 
            {% if item.slug == 'enquete' %}id="enquete-elus"{% endif %}
            class="administration {{ class_type }}-item{% if item_type %} {{ item_type }}{% elif item.slug %} {{ item.slug|slice:"0:6" }}{% endif %}{% if item.href in page.url or item.url in page.url %} cgs-selected{% endif %}{% if item.slug == 'enquete' %} cgs-highlighted{% endif %}"
            {% if item.item_year %}data-year="{{ item.item_year }}"{% endif %}
            {% if item.item_month %}data-month="{{ item.item_month }}"{% endif %}
            {% if item.item_day %}data-day="{{ item.item_day }}"{% endif %}
        >
            {% comment %} Les éléments de liste dans une page de conseil, commission, etc. {% endcomment %}
            {% if class_type == "list" %}
                {% comment %} COMMUN A TOUTES LES PAGES LISTES (FAQ, AMICALE, RESSOURCES, PUBLIC, ADMINISTRATION) {% endcomment %}
                {% include "widgets/blocks/item.html" %}
            {% comment %} Les éléments du menu dans une page d'index (administration ou commissions) {% endcomment %}
            {% else %}
                <a 
                    href="{% if item.slug %}{% slugurl item.slug %}{% endif %}"
                    class="{{ class_type }}-link {{ item_type }}" 
                    title="{% if item.tooltip %}{{ item.tooltip}}{% elif item.slug %}{{ item.slug}}{% endif %}"
                    alt="{{ item.title|default_if_none:'' }}"
                >
                    {% if logo_type %}                               
                        {% include 'widgets/images/logo.html' with intranet_icon=item.logo %}
                    {% else %}
                        {% if "Convocation" in item.title %}
                            {% include 'widgets/images/logo.html' with intranet_icon=settings.dashboard.IntranetIcons.convocation class_type="cgs-nofill" %}
                        {% elif "Compte-rendu" in item.title %}
                            {% include 'widgets/images/logo.html' with intranet_icon=settings.dashboard.IntranetIcons.compte_rendu class_type="cgs-nofill" %}
                        {% else %}
                            {% include 'widgets/images/logo.html' with intranet_icon=item.logo class_type="cgs-nofill" %}                                    
                        {% endif %}
                    {% endif %}
                </a>
            {% endif %}
            
            {% if show_menu_heading and not class_type == "list" %}
                <p>{% if item.heading %}{{ item.heading }}{% else %}{{ item.title }}{% endif %}</p>
            {% endif %}            
        </li>
    {% endif %}
{% endwith %}

web/templates/administration/widgets/main_item.html
<main class="main-content">          
    <div class="cgs-container cgs-{{ item_type }}">
        {% if is_menu %}
            {% include 'administration/widgets/ul_item.html' with index=False %}
        {% else %}            
            <div class="cgs-page">
                {% include 'widgets/images/swap.html' with wrapper=True search=True smooth=True horizontal=True wrap_class="recherche" swap_class="cgs-fixed-icon" swap_initial="Afficher" %}
                {% include "widgets/search/filters.html" %}

                <div class="cgs-list {{ section }}">
                    {% if members %}
                        {% include 'widgets/images/swap.html' with wrapper=True chevron=True smooth=True wrap_class="members" swap_class="cgs-fixed-icon" swap_initial="Afficher" %}
                        <section class="cgs-members cgs-swap-hidden">
                            <div id="action-buttons" class="cgs-action">
                                <button id="cgs-copy" alt="Copy button (clipboard)" title="Copier dans le presse-papier">
                                    {% include 'widgets/images/logo.html' with intranet_icon=settings.dashboard.IntranetIcons.copy class_type="cgs-standard-icon cgs-nofill" %}
                                </button>
                                <button id="cgs-download" alt="Téléchargement des données" title="Télécharger la liste des membres">
                                    {% include 'widgets/images/logo.html' with intranet_icon=settings.dashboard.IntranetIcons.download class_type="cgs-standard-icon cgs-nofill" %}
                                </button>
                                <button id="cgs-print" alt="Imrimer les données" title="Imprimer la liste des membres">
                                    {% include 'widgets/images/logo.html' with intranet_icon=settings.dashboard.IntranetIcons.print class_type="cgs-standard-icon cgs-nofill" %}
                                </button>
                                <div id="emailsContainer" style="display: none;">
                                    {% for _, members_group in members.items %}
                                        {% for member in members_group %}
                                            <span class="email">{{ member.email }}</span>
                                        {% endfor %}
                                    {% endfor %}
                                </div>                                     
                            </div>
                                {% for function, group in members.items %}
                                    {% if group.members %}                 
                                        <h2>{{ function }} - {{ group.size }}</h2>
                                        <ul>
                                            {% for member in group.members %}
                                                <li>
                                                    {% comment %} On crée un mail to {% endcomment %}                                                    
                                                        <a 
                                                            href="mailto:{{ member.email }}" 
                                                            title="Envoyer un mail à {{ member.get_full_name }}" 
                                                            class="email"
                                                        >                                                    
                                                        {% include 'widgets/images/logo.html' with intranet_icon=settings.dashboard.IntranetIcons.mail_to class_type="cgs-zerofill" %}{{ member.get_full_name }} - {{ member.get_municipality_display }}
                                                    </a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}
                                {% endfor %}
                        </section>
                    {% endif %}

                    {% if children.convocation_pages_by_year %}
                        <ul class="{{ class_type }}-box {{ item_type }} {{ section }}">
                            <h2>CONVOCATIONS</h2>
                            {% for year, convocations in children.convocation_pages_by_year.items %}
                                    <h3>{{ year }}</h3>
                                    {% for convocation in convocations %}
                                        {% include 'administration/widgets/li_item.html' with item=convocation item_text=True %}
                                    {% endfor %}
                            {% endfor %}
                        </ul>
                    {% endif %}
                    {% if children.compterendu_pages_by_year %} 
                        <ul class="{{ class_type }}-box {{ item_type }} {{ section }}">
                            <h2>COMPTES-RENDUS</h2>
                            {% for year, compterendus in children.compterendu_pages_by_year.items %}
                                    <h3>{{ year }}</h3>
                                    {% for compterendu in compterendus %}
                                        {% include 'administration/widgets/li_item.html' with item=compterendu item_text=False %}
                                    {% endfor %}
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
        {% endif %}
    </div>
</main>    

web/templates/administration/widgets/news.html
{% if convocation or compte_rendu %}
    <nav class="cgs-news news administration cgs-swap-hidden">
        <ul class="news-box incomming">
            {% if convocation %}
                {% with class_type="news" item=convocation %}
                    {% include 'administration/widgets/li_item.html' %}
                {% endwith %}     
            {% endif %}
            {% if compte_rendu %}   
                {% with class_type="news" item=compte_rendu %}
                    {% include 'administration/widgets/li_item.html' %}
                {% endwith %}
            {% endif %}
        </ul>
    </nav>
{% endif %}

web/templates/administration/widgets/quickbar.html
{% if convocation or compte_rendu %}
    <nav class="cgs-nav quickbar administration">
        <ul class="nav-box incomming">
            {% if convocation %}
                {% with class_type="nav" item=convocation %}
                    {% include 'administration/widgets/li_item.html' %}
                {% endwith %}     
            {% endif %}
            {% if compte_rendu %}   
                {% with class_type="nav" item=compte_rendu %}
                    {% include 'administration/widgets/li_item.html' %}
                {% endwith %}
            {% endif %}
        </ul>
    </nav>
{% endif %}

web/templates/administration/widgets/template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Convocation PDF</title>
    <link rel="stylesheet" href="/static/css/convocation_pdf.min.css">
</head>
<body>
    <main class="main-content">
        <div class="container-fluid viewer">
            <!-- Exemple de contenu pour Watermark et Logo -->
            <img src="http://localhost:8000/media/original_images/marianne_h.png" alt="Watermark" class="watermark">
            <img src="http://localhost:8000/media/original_images/COMCOM-CGS.png" alt="COMCOM-CGS" class="logo">
            <div class="grid-item grid-invitation">
                <div class="grid-invitation-content">
                    <!-- Exemple d'insertion de contenu dynamique pour les hôtes -->
                    <p>Monsieur/Madame Nom Prénom</p>
                    <p>Fonction de l'hôte</p>
                    <p>A</p>
                    <p>Mesdames, Messieurs les</p>
                    <p>Vice présidents/membres de la commission/Maires/délégués</p>
                </div>
            </div>
            
            <div class="grid-item grid-informations">
                <p>Localité</p>
                <p>Le date de création</p>
            </div>

            <div class="grid-item grid-opening">
                <p>Texte d'ouverture personnalisé selon le sous-dir</p>
            </div>

            <div class="grid-item grid-rdv">
                <p>Date et heure du RDV</p>
                <p>Description de la localité</p>
            </div>

            <div class="grid-item grid-odj sous-dir">
                <p>A l’ordre du jour sont inscrits les points suivants :</p>
                <p>Contenu de l'ordre du jour</p>
            </div>
            
            <div class="grid-item grid-closing">
                <p>Texte de clôture personnalisé selon le sous-dir</p>
            </div>

            <div class="grid-item grid-signature">
                <!-- Exemple d'insertion de contenu dynamique pour les signatures -->
                <p>Nom Prénom,</p>
                <p>Fonction.</p>
            </div>

            <div class="grid-item grid-documents">
                <h3>Documents associés :</h3>
                <ul>
                    <!-- Exemple de lien vers un document associé -->
                    <li><a href="/path/to/document.pdf">Titre du document</a></li>
                </ul>
            </div>
            <!-- Exemple de contenu pour l'image de pied de page -->
            <img src="http://localhost:8000/media/original_images/admin_pdp.png" alt="Footer Image" class="footer-image">
        </div>
    </main>
</body>
</html>

web/templates/administration/widgets/ul_item.html
{% load wagtailcore_tags cgs_tags restriction_tags %}

{% if menu %}
    <ul class="{{ class_type }}-box {{ item_type }}{% if is_form %} highlighted{% endif %}">
        {% for item in menu %}
            {% authorized_user item as visible %}
            {% if visible %}
                {% include 'administration/widgets/li_item.html' %}
            {% endif %}
        {% endfor %}
        
        {% if index %}        
            <li class="nav-item {{ child_type }} index{% if item_type != "commissions" and item_type == page.slug %} cgs-selected{% endif %}">
                <a 
                    href="{{page.get_parent.specific.url}}"
                    class="nav-link theme" 
                    title="Retour à l'index" 
                    alt="{{item_type}} Index"
                >                
                {% if page.slug == "commissions" %}                
                    {% include 'widgets/images/logo.html' with intranet_icon=page.get_parent.specific.logo class_type="cgs-bright cgs-nofill" %}
                {% else %}
                    {% include 'widgets/images/logo.html' with intranet_icon=page.get_parent.specific.logo class_type="cgs-bright" %}
                {% endif %}
                </a>
            </li>
        {% endif %}
    </ul>
{% endif %}